<?php
/** @var \Doctrine\Common\Collections\Collection|\Keet\Form\Examples\Entity\Coordinates[] $paginator */

$this->headTitle('Coordinates');

?>

<h1>Coordinates</h1>

<a href="<?= $this->url('coordinates/add') ?>" title="Add">
    Add
</a>

<table class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ID</th>
        <th>Latitude</th>
        <th>Longitude</th>

        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($paginator as $coordinates) : ?>
        <tr>
            <th><?= $coordinates->getId() ?></th>
            <td><?= $coordinates->getLatitude() ?></td>
            <td><?= $coordinates->getLongitude() ?></td>
            
            <td>
                <a href="<?= $this->url('coordinates/view', ['id' => $coordinates->getId()]) ?>" title="View">
                    View
                </a>
                <a href="<?= $this->url('coordinates/view/edit', ['id' => $coordinates->getId()]) ?>" title="edit">
                    Edit
                </a>
                <a href="<?= $this->url('coordinates/view/delete', ['id' => $coordinates->getId()]) ?>" title="delete">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>