<?php
/** @var \Keet\Form\Examples\Form\CoordinatesForm $form */

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('csrf'));

echo $this->formRow($form->get('coordinates')->get('id'));
echo $this->formRow($form->get('coordinates')->get('latitude'));
echo $this->formRow($form->get('coordinates')->get('longitude'));

echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag($form);